# Site settings
title: Theodore LaGrow Online
email: tjlagrow@gmail.com
description: >
  Theodore J. LaGrow - Researcher in Computational Neuroscience, Educator at Georgia Tech, and ML Practitioner.
baseurl: ""                       # the subpath of your site, e.g. /blog/
url: "https://tjlagrow.github.io" # the base hostname & protocol for your site
github_username: tjlagrow

name: Theodore LaGrow
timezone: America/New_York        # more precise than "EST"

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
highlighter: rouge

permalink: pretty

# Collections
collections:
  newsletters:
    output: true
    permalink: /newsletter/:name/
  pages:
    output: true
    permalink: /:name/

include: ["_pages"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
